# Generated by Django 5.2.6 on 2025-09-25 17:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0002_autor_created_at_autor_update_at_comuna_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_categoria', models.CharField(max_length=50)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='codigo',
            new_name='codigo_comuna',
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='comuna',
            new_name='nombre_comuna',
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='nacionalidad',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.nacionalidad'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='detalles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_biblioteca', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=255, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_lector', models.IntegerField(unique=True)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('nombre_lector', models.CharField(max_length=255)),
                ('correo_lector', models.CharField(max_length=255, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.biblioteca')),
                ('id_direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('paginas', models.IntegerField()),
                ('copias', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('fisico', models.BooleanField(default=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.autor')),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.biblioteca')),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(null=True)),
                ('fecha_retorno', models.DateTimeField(null=True)),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.lector')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.libro')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_tipo_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.tipocategoria'),
        ),
    ]
