# Generated by Django 5.2.6 on 2025-10-26 20:05

import aplicacion1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0004_alter_autor_biografia_alter_autor_id_nacionalidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='digito_verificador',
        ),
        migrations.AddField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default='1990-1-1', validators=[aplicacion1.models.validar_mayoria_edad]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lector',
            name='rut_lector',
            field=models.CharField(max_length=12, unique=True, validators=[aplicacion1.models.validar_rut]),
        ),
    ]
