# Generated by Django 5.2.7 on 2025-10-29 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0005_remove_lector_digito_verificador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.direccion'),
        ),
    ]
