# Generated by Django 4.2.25 on 2025-11-06 17:27

import aplicacion1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0006_alter_biblioteca_id_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=None, validators=[aplicacion1.models.validar_mayoria_edad]),
        ),
        migrations.AlterField(
            model_name='lector',
            name='id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.direccion'),
        ),
    ]
